name: Performance

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Execute Test
      run: |
        sh run-performance.sh ${{ github.workspace }}/get.jmx
    - name: Upload Results
      uses: actions/upload-artifact@v2
      with:
        name: report-test
        path: logs/
